# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

# Site settings
url: "https://dhrunlauwers.github.io"
baseurl: ''
title: 'Dhrun Lauwers'
github_username:  dhrunlauwers
email: dhrun.lauwers@gmail.com
description: 'This is my first attempt at a personal blog slash portfolio. Be gentle.'
permalink: pretty
logo: "/icon_dhrun.png"

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_image: "../images/christmas.png"
